### ISSUE TITLE
FreeBSD Binary missing from tar.gz release file

### ISSUE THREAD

**Issue by stephen-hill** [pomerium/pomerium#1289]
Hi

I hope I'm not missing something obvious. I've tried searching existing issues.

The FreeBSD releases do not contain the main pomerium binary, only the promerium-cli binary.

- https://github.com/pomerium/pomerium/releases/download/v0.10.0/pomerium-freebsd-amd64.tar.gz

Is this a bug with the build system, or are these unavailable for a specific reason?

Cheers
Stephen

**Comment by travisgroth** [comment]
Hi @stephen-hill, this is a quirk in the build system.  We do not support FreeBSD for the main binary at this time, though we do for the cli.  The latter is included in the main release bundle, so I think that's accidentally allowing us to create the FreeBSD server archive with only the cli.

We should prevent generating that archive to prevent confusion.

**Comment by travisgroth** [comment]
Currently, the only way to prevent generating the `pomerium` FreeBSD archive is to stop bundling both `pomerium` and `pomerium-cli` binaries in the `pomerium` archive.

It might actually make sense to start publishing just the [bare binaries](https://goreleaser.com/customization/archive/#disable-archiving) or binaries individually compressed rather than trying to include both in the main archive.  

This would be a departure from historical packaging on the server side, but the archives would be more straightforward to understand.  @desimone thoughts?

**Comment by desimone** [comment]
> It might actually make sense to start publishing just the bare binaries or binaries individually compressed rather than trying to include both in the main archive.

> This would be a departure from historical packaging on the server side, but the archives would be more straightforward to understand. @desimone thoughts?

+1 from me. I think it makes sense to publish the `cli` distinctly;
