### ISSUE TITLE
authorize: defer listener startup until directory is loaded

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#1620]
**Is your feature request related to a problem? Please describe.**

When loading directory data from the databroker service at startup, authorize will return 403 errors for group based roles.  In distributed deployments, this can lead to rolling restarts causing perceived outages by end users.

**Describe the solution you'd like**

Ideally, we would not start listening/serving until the initial directory load is complete.  This would provide a signal to external orchestration systems for when the service is truly ready and can help pace rollouts.  It would also prevent a proxy from connecting to an uninitialized authorize service.

**Describe alternatives you've considered**

There may be a more in-band way to do this with gRPC but I think most folks use a TCP port knock for gRPC health/ready checks.

**Explain any additional use-cases**

n/a

**Additional context**

In practices this is only noticeable when there is a large directory, though the behavior is theoretically possible at any size with group based policies.

**Comment by calebdoxsey** [comment]
This isn't possible to do in all-in-one mode because the listener is shared between all services. Defering the listener will also likely lead to the rolling restart issue described above, since it may take a long amount of time for the container to begin listening on the port. In kubernetes this requires setting up a readiness probe with longer timeouts than the liveness probe.

I will implement it when `authorize` is the only service.

**Comment by travisgroth** [comment]
That all makes sense.  Any production deployment should be using some sort of health checking already, so this will create a proper signal for it.  

As a follow up, we may need to expose an option for extending the probe thresholds and timing in the community helm chart.  Currently, we're using the defaults.
