### ISSUE TITLE
JWKS set  should also provide RSA PKI

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium#1626]
At the moment JWKS set has one entry with ES-256 as RSA is quite popular pomerium should support multiple entires in JWKS.

See chat: https://pomerium-io.slack.com/archives/CK92MUAES/p1606498282249300

**Comment by desimone** [comment]
Though RSA is slow, it's ubiquitous. I'm in favor of supporting it but would like to but warning cones around any actual use since (in my limited testing) it's an order of magnitude slower than EC based signing algorithms.

I'd also like to support Ed25519 / Ed448 which although technically is not part of the JOSE spec is propably the best asymmetric signature choice atm.
