### ISSUE TITLE
Authenticate user with bearer token for kubernetes-dashboard

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#1638]
**Is your feature request related to a problem? Please describe.**

I don't know if it is technically feasible but I thought I would ask anyway.

I would like to be able to proxy `kubernetes-dashboard` via pomerium but, instead of using a fixed token with the `set_request_headers` directive in the policy section [as described in the documentation ](https://www.pomerium.com/guides/kubernetes-dashboard.html#pomerium), I am wondering if it would be possible for pomerium to craft a token that reflects the user identity in kubernetes so that kubernetes-dashboard impersonate him with his RBAC restrictions.

I found this which thinks might help: https://github.com/weinong/k8s-dashboard-with-aks-aad#configure-oauth2-proxy

Regards.

**Comment by Ptyool** [comment]
Same wish here ^^

It would be great if a config option could set the Authorization header with the user token, and not set a static bearer token like in the documentation.

We have users with different access right on the k8s api (namespace restriction for example) and we don't want them to have a full access. Currently we are using keycloack-gatekeeper to achieve this but this product is EOL unfortunatelly.

Pomerium have an option which seems close to what we are asking : "pass_identity_headers" but it does not set the Authorization header.

Regards.

**Comment by travisgroth** [comment]
@Ptyool @sylr It turns out kubernetes-dashboard supports passing along Authorization as well as Impersationation headers to the kubernetes control plane.

**Comment by Ptyool** [comment]
Hi @travisgroth ,
I was not aware that "kubernetes_service_account_token_file" was able to invoke impersonation.
So I tried (don't forget to allow used ServiceAccount to do impersonate at k8s rbac level ;-) ), but I was not allowed to do  anything in the kubernetes-dashboard, however I was able to see that pomerium inpersonated me:

![image](https://user-images.githubusercontent.com/48836398/118527277-6c242f00-b741-11eb-9982-d4cdfcd77ff5.png)

So I used the same config to a "debug" backend to see which header are sent, and it seems that Impersonate-group are not sent (rbac on our k8s are done on group claim) :
![image](https://user-images.githubusercontent.com/48836398/118526373-7560cc00-b740-11eb-8252-0b3dd9c01223.png)


By the way, is it possible to use another claim, username for example, instead of email in Impersonate-User header ?

**Comment by Ptyool** [comment]
I tried to staticaly set the Impersonate-Group header with :

      set_request_headers:
         Impersonate-Group: "my-group"

And it works, I was able to access dashboard content.
So there is a problem or a configuration mistake on my side to populate Impersonate-Group header.
I'm sure that Pomerium is able to retrieve groups from access_token because the policy allow access only for some groups :

      allowed_idp_claims:
        groups:
          - my-group
          - my-group-2

Moreover, it is not a Pomerium issue, but we are using oidc user and group prefix on k8s api-server ([https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server](url)) and the impersonate feature does not seems to automatically add the prefix. The group inside Impersonate-Group must contains the prefix (oidcprefix:mygroup).

**Comment by travisgroth** [comment]
> I was not aware that "kubernetes_service_account_token_file" was able to invoke impersonation.

Yep it's not super obvious from the docs, but that's how our integration works.  We're going to update the docs to make this and the improved dashboard setup clearer for everyone.

> So I used the same config to a "debug" backend to see which header are sent, and it seems that Impersonate-group are not sent (rbac on our k8s are done on group claim) :

Would you mind opening a new feature request for populating the kubernetes impersonation headers with group claims?  I'd like to keep that discussion focused.

> Moreover, it is not a Pomerium issue, but we are using oidc user and group prefix on k8s api-server

We usually see folks put Pomerium in front of the API server instead of using underlying OIDC configuration.  Can you expand on your use case for prefixing in the feature request?

**Comment by travisgroth** [comment]
We have a full writeup of this approach now available - https://docs.pomerium.io/guides/kubernetes-dashboard.html.  Closing.
