### ISSUE TITLE
Automatically reauthenticate users

### ISSUE THREAD

**Issue by 1inh** [pomerium/pomerium#1787]
**Is your feature request related to a problem? Please describe.**

I understand that the validity of the session cookie can be set by `COOKIE_EXPIRE`. After this interval (default is 14h), the user must reauthenticate through their IdP.

**Describe the solution you'd like**

Would it possible to automatically log users (who are already authenticated to their IdP) in and what would that entail? The pros of this would be that this all happens in the background, making it a smoother UX.

**Describe alternatives you've considered**

From the user's perspective, it could be somewhat inconvenient to relogin everyday. We could extend the cookie expiration time but that increase the attack surface as session cookies now live longer. A few attack vectors I can see is:
1. CSRF + Clickjacking (I think the risk is the same whether we increase the expiration time or automatically reauthenticate users)
2. Cookie is captured somehow (the risk is definitely larger for long lived cookies)
3. People who are removed from the org could still access the application if the session cookie is active (I haven't verified this but it is based on my understanding of the architecture and flow)

**Comment by calebdoxsey** [comment]
Hi @1inh ,

User sessions are refreshed using the refresh token returned by OIDC. The `COOKIE_EXPIRE` is a security measure, but it can be changed. For example you could set it to a year and, assuming refresh tokens continue to work, you wouldn't need to login again for a year.

Does this work?

**Comment by 1inh** [comment]
> Hi @1inh ,
> 
> User sessions are refreshed using the refresh token returned by OIDC. The `COOKIE_EXPIRE` is a security measure, but it can be changed. For example you could set it to a year and, assuming refresh tokens continue to work, you wouldn't need to login again for a year.
> 
> Does this work?

Hey @calebdoxsey, thank you for the quick response! We can certainly increase the `COOKIE_EXPIRE` field to a year but that introduces more security concern as session cookies are persisted for a long period of time. Also if people leave the org, and still have the cookies, they could still access right? (assuming refresh tokens continue to work)

**Comment by pflipp** [comment]
Hey @calebdoxsey, I think the main issue here is that the pomerium session cookie never gets renewed, once `COOKIE_EXPIRE` is reached the user gets logged out, regardless of the users activity.

renewing the pomerium session cookie on each users activity, would enable us to set a short `COOKIE_EXPIRE` but only logs the user out if the user was inactive for `COOKIE_EXPIRE` period.

what do you think?

**Comment by desimone** [comment]
> Also if people leave the org, and still have the cookies, they could still access right? (assuming refresh tokens continue to work)

That's right. By default, the backend will refresh session tokens every ten minutes so any revoked users should be evicted pretty quickly.  I'm not sure we can solve having both very long lived session lifetimes, and an identity provider that does not revoke refresh tokens. Pomerium's depends on the downstream identity provider to stop issuing new access tokens to users who no longer should have valid user sessions. 

> I think the main issue here is that the pomerium session cookie never gets renewed, once COOKIE_EXPIRE is reached the user gets logged out, regardless of the users activity.

This is much trickier than it seems. 

To rehash how Pomerium currently works a bit....  Pomerium sets two types of client-side session tokens as cookies. 

1. A parent session cookie on the authenticate service. 
2. Child route-scoped session cookies that are derived from the session from the authenticate service. 


A cookie on the authentication endpoint is set so that when an already logged in user tries to access another upstream, they can piggy back off that existing session without having to re-authenticate with the identity provider.  Pomerium sets the _route specific_ cookies only _once_ on callback following a `302` to the authenticate service.

If there is no existing session cookie on authenticate service, the user will reauthenticate with the IdP and set a new user session. Otherwise, the parent session token on the authenticate service is leveraged to create derivative route-scoped sessions for other upstream routes. Being able to use a single IdP session for multiple upstream routes is one of the features that separates Pomerium from other authenticating proxies (e.g. `oauth2_proxy`).  

If I'm understanding correctly, to support the requested functionality we have a few options: 

1. Periodically `302`  the user back to the auth service to "refresh" the user's local session for that upstream. This would imply a different threat model for authenticate and route-scoped local sessions which I don't think buys us anything. And I am almost certain this would would cause all sorts of havoc on any javascript heavy, or single page app.   
2. Have the proxy service constantly resetting the cookie's lifetime by some duration. This would update the lifetime of the sessions that a user is _currently_ interacting with, but not the ones they are not. And here we also have a problem as to what to do with the authenticate session cookie. If we set the expiration on the authenticate based cookie to the value of the backend session, we still have the problem of an extra long lived local session token (if that's the concern). If we set the value of the authenticate cookie to that of the upstream routes, we'd almost certainly have that token expire immediately and you'd lose the parent session, resulting in (nearly) a new managed session for each route. Also, since this would be all client-side, this would only protect user's from malicious outsiders, not an insider who wanted to defeat the inactivity detection system. This
3. Implement some sort of server-side inactivity detection. We could do this by having the authorize service record the last request for a given parent session. This is challenging to manage because it would entail having to effectively write to the databroker an updated timestamp for every request, causing quite a bit of churn on the datastore. The benefits of this approach would be it would apply to all associated user sessions for a given parent session, and would be server side enforced. 


Could you tell me more about the threat model you are trying to address with this type of inactivity detection?

**Comment by pflipp** [comment]
thank you @desimone for the insights.
ok, my PoC then just worked because I had everything under the same domain ;)

I'm with you that `server-side inactivity detection` really is to heavy and `periodically 302 to authenticate service` has performance and client-side drawbacks.

i dont have a clever idea now, maybe we could implement refreshing the cookie for the upstreams and something like a "session keep alive" route which we could periodically call from the frontend?

**Comment by desimone** [comment]
> ok, my PoC then just worked because I had everything under the same domain ;)

Not the worst of situations. A single domain definitely simplifies some assumptions. 

> i dont have a clever idea now, maybe we could implement refreshing the cookie for the upstreams and something like a "session keep alive" route in the authenticate service which we could periodically call from the frontend?

Inactivity detection has been on my radar for a while, but so far I haven't been able to come up with a great solution that will scale. I'm definitely open to ideas and proposals. 

I'm going to close this thread in favor of https://github.com/pomerium/pomerium/issues/1250 which I think better covers the desired functionality.
