### ISSUE TITLE
Impersonate doesn't seem to work

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#181]
**Describe the bug**

After entering a user email or a group in the impersonate input (user and/or group) and clicking on impersonate, nothing happens: it seems there is a 302 that redirects me to the same `/.pomerium` url but I'm still logged as myself and not the impersonated user.

**Expected behavior**

To have my session updated as if I was logged as the user (or the group).

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.0.5
- Server Operating System/Architecture/Cloud: AKS

Configuration file(s): See #152 a always ;)

Logs:
```json
{"level":"debug","fwd_ip":"10.240.0.66","ip":"10.240.0.52","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0","referer":"https://app.xxx.com/.pomerium","req_id":"af0966fc-1965-10f6-3905-5994d80923ea","duration":5.587115,"size":0,"status":302,"email":"","group":"","method":"POST","service":"proxy","url":"/.pomerium/impersonate","time":"2019-06-11T15:27:19Z","message":"http-request"}
{"level":"debug","fwd_ip":"10.240.0.66","ip":"10.240.0.52","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0","referer":"https://app.xxx.com/.pomerium","req_id":"8bc2ad55-c02b-8991-0aeb-27b85d4b5e26","duration":5.144314,"size":12244,"status":200,"email":"victor.noel@xxx.com","group":"all@xxx.com,infra@xxx.com,support@xxx.com","method":"GET","service":"proxy","url":"/.pomerium","time":"2019-06-11T15:27:19Z","message":"http-request"}
```

**Comment by desimone** [comment]
Hi @victornoel , thanks for reporting this. I did some investigation on this and I *think* what's going on is one part bug, and one part confusing user-experience.

- User impersonation is working for me given the above reproduction steps. If you navigate to a routed URL impersonating a user with differing access than the admin user, I am seeing the appropriate response. (e.g. `admin@example.com` does not have access to `httpbin.corp.example.com` but if impersonate `user@example.com` who does have access to that domain, after I impersonate the user and navigate to the underlying URL I am able to see the content. Does this work for you?
- `/.pomerium` does not respect user impersonation. That is to say, it will always see you as your correct user.  This is required so that a user can undo any impersonation and prevents accidental lockout. 
` /.pomerium` does not currently have any type of "success" or "failure" message following submission of the impersonate form. That can be confusing because it's unclear the changes "took" although, if you refresh the page, or come back to the user dashboard the currently active impersonation fields should be present. Adding some sort of submission feedback would likely improve that experience. Maybe a popup message that says "impersonation enabled" or something. 
- I noticed that the incorrect http headers / signed headers were getting set for downstream consumption. I've created a PR to fix that. 

Heres' a screen grab video of what I see (with the updated fixes for headers). 

https://youtu.be/fudXNitrVn0

**Comment by victornoel** [comment]
@desimone some things are different in my experience (with v0.0.5):
- my use case is the complement of the one you show: I am not a member of the authorized group for the protected service and I would like to be included in the group via impersonation in order to access it.
- when I enter a username and/or a group in the `/.pomerium` page and click impersonate, the input fields for impersonation are cleared while in your video they are not.
- once I clicked "impersonate", if I go to the protected app, I'm still unauthorized.

Another unclear thing is: if I impersonate a user, will I be authorized to access app that are authorized to groups this user is a member of, or will this only give me access to app explicitly authorized to this particular user? I would expect the first :)

**Comment by desimone** [comment]
Hmm, this is really strange!

> my use case is the complement of the one you show: I am not a member of the authorized group for the protected service and I would like to be included in the group via impersonation in order to access it.

I tried out the converse, and it similarly worked for me. I used the following `config.yaml`

```yaml
administrators: bdd@pomerium.io

policy:
  - from: httpbin.corp.beyondperimeter.com
    to: http://localhost
    allowed_users:
      - joe@user.com
    allowed_groups:
      - bobby-not-allowed
  - from: external-httpbin.corp.beyondperimeter.com
    to: https://httpbin.org
    allow_public_unauthenticated_access: true
```

https://youtu.be/UDfO0Zv8VPc

> when I enter a username and/or a group in the /.pomerium page and click impersonate, the input fields for impersonation are cleared while in your video they are not.

I've tried Safari, Firefox (this time), and Chrome (last time) and it seems to work for me on OSX. I wonder, are you getting any errors in your browser's developer console? (You shouldn't, since there is no javascript but maybe there's some interaction with `Content-Security-Policy` I'm not thinking of here)....

> Another unclear thing is: if I impersonate a user, will I be authorized to access app that are authorized to groups this user is a member of, or will this only give me access to app explicitly authorized to this particular user? I would expect the first :)

It's the later 😬, as you mentioned, you will impersonate **exactly** the user and groups you entered. This includes non-existant users, and groups. I see why you would expect the first (to check if the user you've selected is indeed part of the groups you think she is), but I also can see use cases for the explicit impersonation of users and groups (what if I want to test what a site would look like if joe@user.com was not part of group `X`) and so on.  

I could go both ways about which type of impersonation to support. The only downside of the implicit approach (where groups are pulled based on a real user) is it would require changes in how some providers provide groups information. For instance, if you are using Google as an IdP it would be relatively trivial to pull back groups for an impersonated user -- however, for Okta -- we currently depend on groups being supplied as part of the identity token during refresh and authorization. We'd have to migrate to using their directory api similar to how it works with google.

Like I said, I'm cool with either approach and I'll let the community decide :)

Still, I can't for the life of me figure out why the form isn't persisting.

**Comment by victornoel** [comment]
@desimone 

> I wonder, are you getting any errors in your browser's developer console?

When I click on impersonate, there is a post to `https://app.xxx.com/.pomerium/impersonate` which results in a 302 with location `/.pomerium` and the browser thus reload the page (and then loose the form, I suppose because of the reload).

The 302 response also contains a set-cookie for `_pomerium` that has a different value than the cookie I have in my storage, but for whatever reason, this is not used in practice by the browser. Same on chromium.

I will do tests using latest master or are you testing  with v0.0.5?

> It's the later, as you mentioned, you will impersonate exactly the user and groups you entered. This includes non-existant users, and groups. I see why you would expect the first (to check if the user you've selected is indeed part of the groups you think she is), but I also can see use cases for the explicit impersonation of users and groups (what if I want to test what a site would look like if joe@user.com was not part of group X) and so on.

Yep, I better understand, this also makes sense, if it's less work (for now) to continue with this, I know I personally won't be bothered by it :)

**Comment by victornoel** [comment]
@desimone another question: can this be related to `allow_public_unauthenticated_access: true`?

**Comment by desimone** [comment]
> Yep, I better understand, this also makes sense, if it's less work (for now) to continue with this, I know I personally won't be bothered by it :)

👍

>  another question: can this be related to `allow_public_unauthenticated_access: true`?

It could in the sense that allow_public_unauthenticated_access skips authentication entirely. No session is loaded, and the route would not be "identity aware". That would only be for that route, though.

**Comment by victornoel** [comment]
> > another question: can this be related to `allow_public_unauthenticated_access: true`?
> 
> It could in the sense that allow_public_unauthenticated_access skips authentication entirely. No session is loaded, and the route would not be "identity aware". That would only be for that route, though.

Sorry, wrong question, I thought you had enabled it for the route we were talking about :)

I think I will try latest dev version of pomerium soon (to also validate everything works as expected for the sign out thing) and see if this issue is really a problem or if it's related to v0.0.5.

**Comment by victornoel** [comment]
@desimone to ensure #170 was working as expected, I tried latest master (2172d64) and after logging out of one my application, I got redirected to the specified `redirect_uri`, but if I go back to the app url, pomerium only told me that I am unauthorized instead of trying to sign me in.

What is strange is that when I went to the pomerium session page, it showed that I was impersonating another user (I just tested it before and it didn't work so I forgot about it).

I had to delete the cookies to make it work again. After that, I could sign out and sign in back without problems.

So basically, it seems that #170 is ok, but because of the problem we are looking at in the present issue, I got impersonating a user once I was signed out (and so pomerium didn't try to sign me in again).

I wonder if it isn't once again a problem of sub-domains and stuffs like that. For the record, this is how things are organised:
- authenticate is on `auth.xxx.com`
- my services are mostly on `a.b.xxx.com`, `c.d.xxx.com` and so on
- I noticed the cookies created 
  - once signed in and connected to `https://a.b.xxx.com` are
    - `_pomerium` for `xxx.com` 
  - after accessing `https://a.b.xxx.com/.pomerium` are
    - `_pomerium` for `xxx.com`
    - `_pomerium_csrf` for `a.b.xxx.com` 
  - after impersonation are 
    - `_pomerium` for `xxx.com`
    - `_pomerium` for `a.b.xxx.com`
    - the csrf one just disappeared

**Comment by victornoel** [comment]
sorry, I made a mistake with the domain of the cookie after impersonating, it's fixed in the comment above

**Comment by desimone** [comment]
> I wonder if it isn't once again a problem of sub-domains and stuffs like that. 

Yes -- I think so. I haven't been able to test it conclusively yet but the behavior you describe makes me think that is the issue.

Ultimately, I think for configurations such as yours we need to have a user supplied `root-domain` configuration key which sets the scope of the authorization cookie -- otherwise, we just enforce subdomain scoped sessions by default. 

If you are okay with it -- I think we can close this and open a new issue to support that feature. Thoughts?

**Comment by victornoel** [comment]
@desimone can't we just use the detected root domain (as with the other issues we have been discussing and we concluded that it should be the super domain of the authenticate service, i.e. xxx.com in my case, corp.pomerium.io in some of your examples, etc) for the cookies?

**Comment by victornoel** [comment]
Following our discussion offline, I concur with the idea of a user supplied root domain configuration.

Two more points/ideas:
- I guess it should be used not only for cookies but also for (sub)domain validation (as in #152).
- If I have as a root domain `a.xxx.com`, authenticate service url shouldn't have to be one level under the root domain, it could perfectly be `auth.b.a.xxx.com`, right?

Also, as I told you, I would even go to the point of removing any "smartness" from pomerium so that the only way to know the root domain is to explicitly specified it in the configuration. I don't think it's a bad design decision because it both removes any unexpected behaviour and ops rarely changes this setting once it is set.

**Comment by victornoel** [comment]
@desimone and also, if this could go into v0.1.0, it would neat :)

**Comment by desimone** [comment]
Hi @victornoel ,

Thank you for summarizing our offline conversation. 

> If I have as a root domain a.xxx.com, authenticate service url shouldn't have to be one level under the root domain, it could perfectly be auth.b.a.xxx.com, right?
> If I have as a root domain a.xxx.com, authenticate service url shouldn't have to be one level under the root domain, it could perfectly be auth.b.a.xxx.com, right?

Exactly. 

>  I would even go to the point of removing any "smartness" from pomerium so that the only way to know the root domain is to explicitly specified it in the configuration. I don't think it's a bad design decision because it both removes any unexpected behaviour and ops rarely changes this setting once it is set.

Your point about user confusion (especially using certain configurations) is well taken. However, to preserve backwards compatibility and to default to what I believe is the most secure configuration (without the user having to understand the implications of cookie session scope), I think it makes sense to still infer the rootDomain as the full tld - 1 (e.g. rootDomain would be `corp.pomerium.io` if authenticate is `authenticate.corp.pomerium.io`) unless a `rootDomain` is explicitly set.  

@victornoel Thoughts?

**Comment by victornoel** [comment]
@desimone yep, I see no problems with keeping the current behaviour in case `rootDomain` is not explicitly set (except that it is more complexity to maintain ;).

**Comment by victornoel** [comment]
@desimone could we get the solution discussed here for 0.1.0?

**Comment by desimone** [comment]
@victornoel See #206 ; implementation is slightly different that we discussed but the result should be the same.

**Comment by victornoel** [comment]
@desimone yep, so instead of a root domain, we specify a cookie domain, which provides the same result as what we discussed above. That seems good yes (even though I feel like the code may be much simpler if the concept of root domain was used through the whole pomerium codebase, but you know better :)
