### ISSUE TITLE
Followed synology setup instructions - access only works from external networks.

### ISSUE THREAD

**Issue by Esteth** [pomerium/pomerium#194]
After following the synology setup guide I am able to access the reverse proxy and sign in from my mobile phone connected to mobile network, but any device on my WiFi times out when attempting to load the same URL.

I'm not sure if this is a routing misconfiguration somewhere, but I'm pretty dumb about networking and I suspect some of the guide readers are too, so this might be a good opportunity to improve the docs if we can fix it for me.

- Pomerium version (retrieve with `pomerium --version`):
"latest" according to synology UI

- Server Operating System/Architecture/Cloud:
Synology DSM / Docker

Configuration file(s):

- from: tv.nas.bar.net
  to: http://tv:8989
  allowed_users:
  - foo@gmail.com
  - bar@gmail.com
- from: movies.nas.bar.net
  to: http://movies:7878
  allowed_users:
  - foo@gmail.com
  - bar@gmail.com
- from: books.nas.bar.net
  to: http://books:5299
  allowed_users:
  - foo@gmail.com
  - bar@gmail.com
- from: get.nas.bar.net
  to: http://get:6789
  allowed_users:
  - foo@gmail.com
  - bar@gmail.com

**Comment by desimone** [comment]
Hi @Esteth 

As you hinted at in your issue -- this looks like a network configuration issue (vs a Pomerium issue) and is rather difficult to debug just because there are *so many* types of possible network configurations.

However, my hunch is that your DNS is resolving `movies.nas.bar.net` differently when it is behind the network vs when your mobile is on the internet or your router is routing traffic internally differently vs externally.

You can try checking DNS resolution from the command line as follows using the `dig` command. 

```bash
$ dig httpbin.int.nas.bdd.io
....
; QUESTION SECTION:
;httpbin.int.nas.bdd.io.		IN	A

;; ANSWER SECTION:
httpbin.int.nas.bdd.io.	3572	IN	CNAME	nas.bdd.io.
nas.bdd.io.		32	IN	A	47.147.203.72

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jun 27 20:10:33 CEST 2019
;; MSG SIZE  rcvd: 91```
```

Where `SERVER: 127.0.0.1#53` is the effective dns server.

You can try to see what a public DNS service like or [google](https://developers.google.com/speed/public-dns/) would return by explicitly settings the name server. 

```bash
dig @8.8.8.8 httpbin.int.nas.bdd.io

; <<>> DiG 9.10.6 <<>> @8.8.8.8 httpbin.int.nas.bdd.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10787
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;httpbin.int.nas.bdd.io.		IN	A

;; ANSWER SECTION:
httpbin.int.nas.bdd.io.	3575	IN	CNAME	nas.bdd.io.
nas.bdd.io.		35	IN	A	47.147.203.72

;; Query time: 46 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jun 27 20:14:23 CEST 2019
;; MSG SIZE  rcvd: 81
```

Hope that helps.

**Comment by desimone** [comment]
Hi @Esteth were you able to resolve the issue you were having?

**Comment by Esteth** [comment]
Thanks Desimone - It turned out to be an issue with my router - it does not support a NAT feature which allows it to resolve external IPs back into the internal network.

As a workaround, I've had to run my own DNS server internally which "hijacks" the real DNS entries and gives the internal IPs instead.
