### ISSUE TITLE
Is pomerium can handle auth for gRPC services?

### ISSUE THREAD

**Issue by lokkersp** [pomerium/pomerium#2060]
Hello everyone. 
I would like to ask about authentication for services, which don't have a UI and used by machines through pomerium(CE).
In my case, we already have this auth flow:
`[internet] -> traefik ingress -> pomerium [forward auth middleware] -> keycloak as an idp.`
And it's working perfectly for cases with UI auth flow.
At some point, I want to provide the ability to call our backend services directly with the same auth scheme. The protocol for these services is gRPC(typically but also it's an HTTP). 

I didn't find out how to support this scheme properly for gRPC within pomerium. Where I can read something about it? Is this scheme possible?

**Comment by calebdoxsey** [comment]
Hi @lokkersp ,

When [`pass_identity_headers`](https://www.pomerium.io/reference/#pass-identity-headers) is enabled we attach a `x-pomerium-jwt-assertion` header, which contains some authentication information, for example the session id, user id and groups. We also pass these as separate headers (`X-Pomerium-Claim-*).

Since gRPC is just HTTP/2 underneath, you can retrieve these header values with 

```go
md, ok := metadata.FromIncomingContext(ctx)
rawJWTs := md.Get("x-pomerium-jwt-assertion")
```

When coupled with [gRPC web](https://github.com/grpc/grpc-web) it should be possible to call gRPC services from the frontend, through Pomerium, to the backend and use the headers to confirm the user's identity.

Is this what you had in mind?

**Comment by moisei** [comment]
@calebdoxsey 
would you have time to discuss the issue via some chat?
I am feeling it will be easier to explain to you our setup and the problem
