### ISSUE TITLE
Differences between Forward Auth and Proxy mode when using Pomerium as an Oauth Proxy

### ISSUE THREAD

**Issue by mahlakka** [pomerium/pomerium#2348]
Trying to understand the pros and cons of using the Forward Auth mode vs Proxy Mode. 

I've currently setup Traefik and Pomerium with Forward Auth and it's working great. Are there any advantages/security benefits with switching to Proxy Mode?

**Comment by travisgroth** [comment]
Hi @mahlakka,

The pros of using Pomerium's proxy are primarily functional/operational.  Going forward it will increasingly become the recommended configuration, as we have a lot more control with our own proxy:

- Higher performance due to decreased service hops
- Less configuration required - only Pomerium rather than Pomerium + third party proxy
- Less fragile - forward auth is very complicated to get right and subject to third party behavior changes
- TCP/SSH support 
- Kubernetes API server support

Broadly speaking, most - if not all - of the limitations that made forward auth desirable in the past have been addressed over the last few versions of Pomerium.  There are still environments where it may make sense but they should be rare at this point.
