### ISSUE TITLE
The page at 'https://' was loaded over HTTPS, but requested an insecure resource 'http://' ...

### ISSUE THREAD

**Issue by leiless** [pomerium/pomerium#2349]
## What happened?
After a login session expired, normally we need to issue a refresh token or require login again.
When my cookie expired, the browser complained about `The page at 'https://' was loaded over HTTPS, but requested an insecure resource 'http://' ...`

## What did you expect to happen?
A normal re-login.

## How'd it happen?
1. Login.
2. Wait until the cookie/token expires.
3. Met `... was loaded over HTTPS, but requested an insecure resource ...` error

## What's your environment like?

- Pomerium `v0.10.0`
- CentOS 8 x86_64

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://bogus.foobar.com

debug: true

certificates:
  - key:    bogus.foobar.com+3-key.pem
    cert:   bogus.foobar.com+3.pem

idp_provider: foobar
idp_client_id: 5dabc3a8-414d-4ae4-a061-6a231187144a
idp_client_secret: v9ExHPTKfOAcSP9QfMu0Yni40mUXtxCXypE9jRqxFA0=
idp_provider_url: https://www.foobar.com
idp_service_account: pomerium-bot@foobar.com:jaOii3MPFlWk

cookie_expire: 168h # 7 days

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: jwQKxJu/X6sUNtfk6ckdGK6m5X9nzL+Pc91bTWoxkLI=

jwt_claims_headers: ["email", "sub", "groups"]

policy:
  - from: https://bogus.foobar.com
    to: https://log-decryptor.foobar.com
    pass_identity_headers: true
    allowed_groups:
      - 1
```

## What did you see in the logs?

Currently, I can't see the logs. but there are some screen snapshots that might be helpful:
![image](https://user-images.githubusercontent.com/38041294/125037603-ef6d5b80-e0c6-11eb-9b5c-cecf3c66fed0.png)
![image](https://user-images.githubusercontent.com/38041294/125037618-f4320f80-e0c6-11eb-8516-d4b98d1b4bd9.png)

## Additional context

As you can see, I used a custom identity provider(i.e. `foobar`), which I implemented to fulfill my company's needs.
`foobar` identity provider's code is somewhat based on GitHub identity provider.
Back then when we implement this identity provider, Pomerium latest release is `v0.10.0`(`4d36a5a8506d953907d50424e8a7377fbc1372fa`).

**Comment by leiless** [comment]
Accoording to the docs, I saw a suspicious option [`cors_allow_preflight`](https://www.pomerium.io/reference/#cors-preflight), but I don't know if it's related to this problem.

**Comment by calebdoxsey** [comment]
It looks like the service worker is making a request of some kind. Because the session is no longer valid,.that request goes through the login flow.

Do you know what the request was for?

We have some recent code written in authorize to treat certain requests as non-interactive so that an http error is returned instead of redirecting through the login flow. This is generally easier to detect by single page apps. For example this solved a similar problem with Grafana.

However that code is pretty conservative in what it considers interactive or not. Currently it only handles obvious ajax calls and grpc. With more details about the triggering request we may be able to add another exception.

You may also be able to fix this by adjusting a `fetch` call to explicitly ask for JSON.

Finally if the request being made is for something that doesn't require a valid user (like a static assets directory) you could add another public route policy using a path prefix on the assets directory.

**Comment by leiless** [comment]
After an internal discussion, we figured out that maybe it's because of some settings due to Nginx URL rewriting, for example, if I using a relative URI, Nginx may complete it with a full URL, and the protocol may use `http://`.

I suspect the requests for assests still need to check for a valid session since our `log-decryptor` service requires a login to use.

**Comment by travisgroth** [comment]
Thanks @leiless.  Let us know if you need anything further on this.
