### ISSUE TITLE
tracing: spans are disjointed in jaeger / zipkin

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2372]
@desimone commented on [Fri Jul 16 2021](https://github.com/pomerium/pomerium-console/issues/1605)

## What happened?

When exploring spans created in Pomerium, the proxy'ing, and authorization context spans do not seemed to be linked across services (even in all in one mode). 

<img width="1592" alt="Screen Shot 2021-07-16 at 1 55 33 PM" src="https://user-images.githubusercontent.com/1544881/126007601-5c98d9f0-d4d2-482d-a47f-324aeb71b5c2.png">
<img width="1592" alt="Screen Shot 2021-07-16 at 1 55 30 PM" src="https://user-images.githubusercontent.com/1544881/126007608-2d21fc56-58e0-417a-9337-5c2077f3152e.png">
<img width="1592" alt="Screen Shot 2021-07-16 at 1 57 08 PM" src="https://user-images.githubusercontent.com/1544881/126007719-c48aa8ab-71d5-4bee-9564-62baf9bbc700.png">

## What did you expect to happen?

I expect span contexts to be linked between services (envoy, proxy, authorize, etc). 

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

pomerium: v0.14.0-125- g86b56ffd-dirty+ 86b56ffd
envoy: 1.17.3+d164542c107a44b6560b6711ed2275dc51afd6fe4645e493e5f367868603d00c

## What's your config.yaml?

```config.yaml
# tracing_provider: zipkin
# tracing_zipkin_endpoint: http://jaeger:9411/api/v2/spans
# tracing_sample_rate: 1
```

```docker-compose.yaml
  jaeger:
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by calebdoxsey** [comment]
I don't think this is actually a bug but I don't know enough about Jaeger to prove that. All the code to connect spans is there and being called, so the behavior is working as the libraries were to written to work. I guess we want tracing to work differently than that. I will implement custom code to try and make this work as the issue is asking. (but I don't really know what I'm doing so :man_shrugging: )

**Comment by desimone** [comment]
> I don't think this is actually a bug but I don't know enough about Jaeger to prove that.

Do you think this is a jaeger bug?

> All the code to connect spans is there and being called

That's what I thought as well. 

>  so the behavior is working as the libraries were to written to work.  I guess we want tracing to work differently than that. 

Could you elaborate there? 

> I will implement custom code to try and make this work as the issue is asking. (but I don't really know what I'm doing so 🤷‍♂️ )

I was thinking maybe we just missed a context propagation somewhere since I do see some cross envoy / pomerium control plane spans between authN and envoy. But maybe I'm mistaken? 

<img width="1672" alt="Screen Shot 2021-07-19 at 4 22 43 PM" src="https://user-images.githubusercontent.com/1544881/126239675-ec80b44b-09e5-429c-9227-74157bfd4030.png">

**Comment by calebdoxsey** [comment]
> Do you think this is a jaeger bug?

I don't know.

> Could you elaborate there?

I created a PR to fix the issue. I manually parse out the headers and build the spans instead of relying on `ocgrpc`. I have no idea if this is right or not. AFAIK Open Census is a dead library.

> I was thinking maybe we just missed a context propagation somewhere since I do see some cross envoy / pomerium control plane spans between authN and envoy. But maybe I'm mistaken?

All the code is there. It doesn't work. I don't know why. I stopped using it.

**Comment by travisgroth** [comment]
Some context.  I suspect the zipkin tracer in envoy is the problem.  We changed to it [here](  https://github.com/pomerium/pomerium/commit/c3286aa355983db5e2467096a12b434885e8eaef#diff-98c1638962b19c622bb23546f5d6932de7076735dc0b81f6c75992875c2910f8L40-L50).  We made this change because the zipkin export for the OC tracer is deprecated.

There was explicit configuration for grpc trace bin, which probably carried the `ext_authz` context correctly.  However, I don't see a way to tell the zipkin tracer to do that.  That's probably why this doesn't work as expected now.
