### ISSUE TITLE
authorize: add additional tracing spans

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2383]
**Is your feature request related to a problem? Please describe.**

Currently, Pomerium adds a good amount of tracing information to requests. One noticeable exception to that is around the authorization decision. Most of the `authorize.grpc.check` function is unaccounted for. 

<img width="1681" alt="Screen Shot 2021-07-20 at 1 01 27 PM" src="https://user-images.githubusercontent.com/1544881/126564104-d93c34f0-7405-4265-8c06-5e5ff3d8bc25.png">

**Describe the solution you'd like**

Add additional tracing spans to the authorization service, and instrument rego evaluation if practical / possible. 

**Describe alternatives you've considered**

**Explain any additional use-cases**

N/A

**Additional context**

- #2265 
- #2372

**Comment by calebdoxsey** [comment]
Fixed with https://github.com/pomerium/pomerium/commit/c7a8f11d9aa156771d4a0ba23ef35151456d250a

Rego does have additional instrumentation and tracing capabilities, but they were very low level. I think having spans for each evaluation will be sufficient. Custom policies are tagged with a checksum so theoretically we could identity which policy is slow.
