### ISSUE TITLE
Clarify Istio TCP Connect process

### ISSUE THREAD

**Issue by eddiewang** [pomerium/pomerium#2387]
Right now, Istio support seems to end at HTTP services. When we want to proxy TCP based services, the istio-ingressgateway seems to respond back with:

`[2021-07-22T22:36:00.297Z] "CONNECT - HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "x.x.x.x" "Go-http-client/1.1"`

[Initial research](https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/
) showed a possible way of using a `ServiceEntry` to allow CONNECT requests through.

However, this seems to be aimed at external http proxies, rather than letting a CONNECT request through the istio-ingressgateway and into the IAP.

I also found Envoy filters here that seem to suggest CONNECT passthrough support. Here is an example [config](https://github.com/envoyproxy/envoy/blob/a8033fa8e44406ba6448cf3110037cb79f81ff39/configs/proxy_connect.yaml
). [EnvoyFilters](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) can be modified directly in Istio, so this seems like a possible way of making this work as well.

It would be great to get some clarity on how we can enable TCP based services with an Istio-based stack :)

**Comment by travisgroth** [comment]
Hi @eddiewang this should be resolved with our new guidance for setting up Pomerium and Istio together.  https://github.com/pomerium/pomerium/pull/2943.

The crux of the solution is that we now have a way to deploy Pomerium at edge (bypassing the Istio proxy for inbound traffic) but still taking full advantage of the rest of the service mesh for all the rest of the traffic flow.  That should allow TCP connect to "just work" as we're back in control of the HTTP request termination.

To be clear, this utilizes Pomerium and Pomerium Ingress Controller as an alternative to the Istio Ingress Gateway rather than in conjunction with it.
