### ISSUE TITLE
Unable to pass identity headers

### ISSUE THREAD

**Issue by galan** [pomerium/pomerium#2517]
## What happened?
There is no email-address passed, neither as request-header nor as jwt field.

## What did you expect to happen?
I want the email-address being passed by the proxy to the downstream application.

## What's your environment like?
- pomerium in kubernetes, using the helm-chart 20.1.0
- that's pomerium 0.14.4
- I do have the annotation `ingress.pomerium.io/pass_identity_headers: "true"` in the ingress, which generates the policy config (see below)
- I have also configured the `config.extraOpts.jwt_claims_headers` in the helm values to `["email", "groups", "user"]` which is also in the generated k8s secret (see below)
- /.pomerium shows me the correct email address

## What's your config.yaml?

```config.yaml
shared_secret: xxx
address: :443
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem
policy:
- from: https://app.my-domain
  to: http://app.default.svc.cluster.local:8080
  allowed_domains:
  - my-domain
  pass_identity_headers: true
... (more policies)
authenticate_service_url: https://authenticate.my-domain
cookie_secret: xxx
cookie_expire: 335h0m0s
idp_client_id: xxx
idp_client_secret: xxx
idp_provider: google
idp_provider_url: https://accounts.google.com
idp_qps: 0
authorize_service_url: https://pomerium-authorize.my-namespace.svc.cluster.local
certificate_authority_file: /pomerium/ca.pem
jwt_claims_headers:
- email
- groups
- user
tracing_zipkin_endpoint: ""
grpc_address: :443
forward_auth_url: https://forwardauth.my-domain
databroker_service_url: https://pomerium-databroker.my-namespace.svc.cluster.local
databroker_storage_type: memory
```

## What did you see in the logs?
Nothing special

## Additional context
Pomerium is basically working for all configured ingresses, just unable to get the email.

**Comment by galan** [comment]
Tried with the latest v0.14.8 and v0.15.1 images for the pomerium-proxy, as well as the different `jwt_claims_headers`, without luck.

**Comment by calebdoxsey** [comment]
This is difficult to debug, but a few possibilities:

1. Are the `idp_scopes` being customized? `email` is required in order to fill in the identity token claim.
2. I think a signing key is required for claim headers to work. I believe with the helm chart that should be automatically generated, unless it was overwritten. Are you using a custom signing key?
3. It doesn't look like you're using `idp_service_account` which means you're not querying the Google API for user information. The product should still work even without this information, since email should be populated via the identity token claims, but if you were using the directory information it's necessary to have the right permissions on the service account. It might be possible if missing the scopes on the service account that email wouldn't be populated.

**Comment by flecno** [comment]
@galan Is this configured behind a other ingress controller like nginx with external auth? I think you can't expect the headers then
