### ISSUE TITLE
proxy: handle double slash in path

### ISSUE THREAD

**Issue by alagendijk-minddistrict** [pomerium/pomerium#262]
**Describe the bug**

When requesting a URL through pomerium that contains a double slash in the path pomerium redirects this request to the same URL with just a single slash
example: https://test.corp.example.com/foo//bar will be redirected to https://test.corp.example.com/foo/bar

**To Reproduce** Steps to reproduce the behavior:

1. Requested https://test.corp.example.com/foo//bar
2. Got redirect to https://test.corp.example.com/foo/bar

**Expected behavior**
Pomerium proxies a URL containing // in the path to the endpoint instead off redirecting it.

**Environment:**

- Pomerium version: v0.2.1+47f7a44
- Server Operating System/Architecture/Cloud: Ubuntu 18.04

Logs(s):

```text
10:32AM DBG http-request duration=0.215143 email= group= ip=<removed> method=GET req_id=40ccf958-5809-e524-9995-fe9592701cdb service=all size=43 status=301 url=/foo//bar user_agent="<removed>"
10:32AM DBG http-request duration=34.982312 email=<removed> group="<removed>" ip=<removed> method=GET req_id=f339ff81-11c4-eb4b-3c0a-0d6de7316960 service=all size=233 status=404 url=/foo/bar user_agent="<removed>"
```

**Additional context**

According to https://tools.ietf.org/html/rfc3986#section-3.3 a request path can not start with a double slash, but can have a double slash somewhere else in the path.
I encountered this issue with Jenkins, which does a reverse proxy check to a URL which contains its own full URL in the path.

**Comment by desimone** [comment]
@alagendijk-minddistrict Just to confirm, is the double slash either immediately following the domain or at the end of the path?

I don't think [url.Parse is doing this](https://play.golang.org/p/4k3zAGOYaRB) but it could be happening within the reverse proxy by [singleJoiningSlash](https://golang.org/src/net/http/httputil/reverseproxy.go?s=2687:2730#L79) but I wouldn't expect that in the middle of the string.  Or, the path is being cleaned by Go's default ServeMux.

https://github.com/golang/go/blob/1962dc88eb89cd37d3f9f85e8e4b7ad4915db089/src/net/http/server.go#L2212-L2232

I haven't figure it out yet but I'm looking into it :)

**Comment by alagendijk-minddistrict** [comment]
According to the RFC (if I understand it correctly) a double slash following the domain is not allowed. So in that case a redirect seems logical to me.
In my example the double slash is somewhere in the middle of the path. The redirect also happens with the double slash the end of the path

**Comment by desimone** [comment]
`ServeMux` is definitely the culprit here and seems to be doing the _wrong_ ™️  thing here with respect to the RFC. Unfortunately, it looks like this issue is a [WONTFIX](https://github.com/golang/go/issues/19481) for the go team so any approach we take will have to be away from standard lib.

1. Maintain our own version of ServeMux that does not do the bad thing. Not a huge fan of this because we risk getting out of sync with upstream and lose many of the benefits of using standard lib in the first place
1. Use an alternative mux such as gorilla or chi. Both are high quality and should be more or less a drop in replacement but entail an additional third party dependency. 

Although it's a pain, and is a rather unusual edge-case, I think we should support the RFC. 

Thoughts? @alagendijk-minddistrict @travisgroth  ?

**Comment by alagendijk-minddistrict** [comment]
Sorry for the late reply, I was on vacation.
Following the RFC has my preference. This is kind of an edge case but predictable behavior for a proxy is a big plus.

**Comment by desimone** [comment]
@alagendijk-minddistrict no worries. I have a PR coming soon that should fix this issue.
