### ISSUE TITLE
Alternate Pomerium URL not presenting valid SSL certificate

### ISSUE THREAD

**Issue by kevintater** [pomerium/pomerium#3473]
## What happened?
Using "Alternate Pomerium URL" in the desktop app or --pomerium-url in the CLI for a tcp connection results in a TLS error and requires disabling tls verification to function. Pomerium proxy will return a self signed certificate. 

## What did you expect to happen?

Using the "Alternate Pomerium URL" or  "--pomerium-url" feature will trigger the Pomerium proxy service to serve a defined certificate for the external proxy dns entry or the certificate for the route entry. 

## How'd it happen?

1. Create TCP route in Pomerium Enterprise console.
2. Upload a valid certificate for the route
3. "From" address in the route is not externally resolvable
4.  Start Pomerium desktop app
5. "Alternate Pomerium URL" help hover text reads "OPTIONAL: Pomerium proxy URL. Useful if the Destination URL isn't publicly resolvable"
6. Enter route details including "Alternate Pomerium URL" with the externally resolvable address for the proxy (proxy.company.com)
7.  Click Save/Connect 
8. Desktop application reports "tcptunnel: listening on 127.0.0.1:2022"
9. Try to ssh to 127.0.0.1:2022 and receive error:

kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 2022

11. Look at log section in the desktop app:

tcptunnel: error serving local connection error="tcptunnel: failed to establish connection to proxy: x509: certificate is valid for * and not proxy.company.com"

12. Check "Disable TLS Verification"
13. Connection succeeds and tcp connection will function

This issue is repeatable in the cli app following the similar workflow and setup. 

## What's your environment like?

Pomerium Enterprise v0.17.1-1648757173+018cb6ed
Pomerium v0.17.1-1648674931+9fd09459

Ubuntu OS
Running in AWS and on prem in KVM.

Proper certificates present for route host
Proper certificate present for external proxy dns
Certificate for external proxy dns added to proxy service config.yaml configuration.
All other non tcp routes and pomerium functionality work correctly.

Note: Wildcard certificates are not allowed in our environment. 

## What's your config.yaml?

```config.yaml
---
address: ":8443"
metrics_address: ":9090"
services: proxy
shared_secret: REDACTED
certificate_file: "/etc/pomerium/PROXY.COMPANY.com.crt"
certificate_key_file: : "/etc/pomerium/PROXY.COMPANY.com.key"
authenticate_service_url: https://REDACTED
authorize_service_urls:REDACTED
signing_key: REDACTED
cookie_secret: REDACTED
#autocert: true
idp_service_account: REDACTED
idp_refresh_directory_interval: 90m
idp_refresh_directory_timeout: 10m
databroker_service_urls:REDACTED
```

## What did you see in the logs?

```logs
No logs present in server
```

**Comment by cfanbo** [comment]
Please check whether the routing certificate is correct or whether the certificate matches the domain name

**Comment by calebdoxsey** [comment]
Somewhat related: https://github.com/pomerium/internal/issues/909

**Comment by desimone** [comment]
My understanding.

- There's no route for `proxy.pomerium.com`
- There is a certificate in the bundle for `proxy.pomerium.com`
- We are falling back to a catch all self-signed certificate (since there is no route).

An option could be...

- Have envoy match any bundled certificate name w/ an empty virtualhost (n.b. no actual route will exist).
- Route to a `404` similar to what we do today with the self-signed cert and `*`

Another option could be to:

- Expand the pomerium `tcp://` syntax to include the "bastion" / "pass-through" server (here `proxy.pomerium.com`) in the path of the URL. Then we can create the correct routing and virtual host record to properly serve the certificate. For example `tcp+https://proxy.pomerium.com/ssh.pomerium.com:22` ; but not sure if we can embed the port directly like that in a URL path.  Maybe there's a better syntax to support two ports. 


My preference is for the later.

**Comment by desimone** [comment]
After some internal and external conversations, it seems like `tcp+https://proxy.pomerium.com:8443/ssh.pomerium.com:22` is the desired path (pun intended) here :)

**Comment by desimone** [comment]
This requires changes to the `cli` and desktop client too.

**Comment by calebdoxsey** [comment]
This should be implemented now and will be in the next release.
