### ISSUE TITLE
Debian builds are broken - `GLIBC_2.29' not found (envoy)

### ISSUE THREAD

**Issue by kevin-olbrich** [pomerium/pomerium#3934]
## What happened?
> /tmp/pomerium-envoy325626970/envoy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/pomerium-envoy325626970/envoy)

## What did you expect to happen?
Successfull service startup.

## How'd it happen?

Upgrade to Pomerium 1:0.21.0-1~rc1.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):

> pomerium: 0.21.0-rc1-1674048966+e8004bbb
> envoy: 1.24.0+05e1343657086268edaa16a1e8a1429d9c8f6e50a44f492cf629fdc71da2ecdc

- Server Operating System/Architecture/Cloud:

> Debian GNU/Linux 10 (buster)
> Debian GNU/Linux 11 (bullseye)

## What's your config.yaml?

not relevant

## What did you see in the logs?

```
{"service":"envoy","name":"envoy","time":"2023-02-02T13:28:00+01:00","message":"/tmp/pomerium-envoy2389820116/envoy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/pomerium-envoy2389820116/envoy)"}
{"level":"info","pid":15811,"time":"2023-02-02T13:28:00+01:00","message":"envoy: start monitoring subprocess"}
{"level":"fatal","pid":15811,"time":"2023-02-02T13:28:00+01:00","message":"envoy: subprocess exited"}
```

## Additional context

Downgrading via `apt install pomerium=1:0.20.0-1` fixes the issue.

Maybe it would also be a good idea to move non-release versions to their own package feed instead of mixing them with release builds.

**Comment by desimone** [comment]
1. We don't want to support old versions of (released) Envoy. While the API changes between 1.23 and 1.24 are not large today, they may be in the future. It's too much of a maintenance burden.
2. We could _try_ to compile our own versions of envoy against the oldest possible version of gllibc. It may not work, and likely will not work. And we would be running a version of Envoy totally different than the community. This is too much of a burden for our team.
3. Static binding which seems to be discouraged by the Envoy team and unsupported.


We don't have many great options here, which is unfortunate because I would like to support all the major non-EOL'd versions of linux.
