### ISSUE TITLE
config: Dynamic Config Update through Kubernetes Annotations

### ISSUE THREAD

**Issue by commixon** [pomerium/pomerium#425]
**Is your feature request related to a problem? Please describe.**

_NOTE: This use-case is mostly kubernetes-specific._

This is not a problem per se, but it's kind of a hindrance that we want to overcome. To describe our use case: We have a number of microservices, portals and exposed APIs. We want to fully automate the appending of policies in pomerium proxy's config. Ideally we would like this update to be "declarative", that is a service exposing the information that "I'd like to be served behind pomerium proxy". As it holds right now, for every new service/portal we have to update the Kubernetes Configmap. However, in our org we have a lot of different engineering teams and we would like to remove ourselves (the DevOps/SRE team) from the whole pipeline.

**Describe the solution you'd like**

I would suggest a Kubernetes event watcher, where it watches for configmap changes cluster-wide and filter them according to a given annotation (e.g. `pomerium-reload: true`). After that it should read the annotated configmap and append it to the policies part of pomerium's configmap. That's a very high level overview of my initial thought.

**Describe alternatives you've considered**

We've considered to add a step in our pipeline (last step before deployment) that patches the pomerium configmap with our desired policies. This however is not that much of a cloud-native  solution :) 

**Additional context**

I am willing to provide such a functionality if you'd like. To tell you the truth I have not made my mind as to where this watcher/sidekick/reloader's code would lie. In the same repo and build another command under `cmd`, in a completely different repo inside the `pomerium` org? I have no strong opinions here, I would propose the latter to tell you the truth.

**Comment by travisgroth** [comment]
Hi @commixon 

This is actually something I've been working on in the background, and the end goal makes total sense.  This is as good a place as any to dump my thoughts.  I've tried to structure them but some of this probably needs a diagram or further discussion to make sense.  

<Wall of Text>

## General
- Keep as close to the `Ingress` resource type as possible to start.  Being mostly compatible with other tools and charts is important for adoption and ease of use.
  - The route of a custom Ingress-like CRD (see Istio and Traefik) should be avoided.  Associate CRDs to native types instead of trying to replace them
- Build in support for `Service` resources, as Pomerium is likely to support non-HTTP endpoints soon.
- Pomerium as currently written can act as an Ingress, though with certain limitations.
  - Does not support multiple SSL certs
  - Does not support hot reload of cert(s)
  - Does not do path based routing
  - Does not have actual load balancer capabilities
- Goal of being first class part of the helm chart.
- Since there is a long road to becoming a fully functional ingress controller, look for incremental phases to delivery functionality.
- Assume functionality will go beyond just Ingress control, so call it `pomerium-operator`.

## Deployment models

Not all of these are great, but the different possibilities are worth enumerating.

- Forward Auth
  - Allow a more well known ingress controller to offload auth to Pomerium without losing functionality.
  - pomerium-operator can watch the same ingress class as another main ingress controller and update config based on annotations.
  - No worrying about SSL termination or other missing features.
  - Ingress resources will need both Pomerium and controller specific annotations.  A mutating webhook could help with this.

- Simple Ingress
  - Pomerium is deployed as a `LoadBalancer` L4 service.
  - pomerium-operator watches Ingress resources and consumes them as any other ingress controller.
  - Limitations noted above until we add features to the proxy service.  This may be okay for orgs with a big wildcard cert and simple Ingress resource needs.

- Double Ingress ([internet]->[nginx]->[pomerium])
  - A third party ingress controller is deployed watching one ingress class (a), and pomerium-operator is deployed watching a second one (b).
  - An application deploys an Ingress resource targeted to class (a) but pointing the Backend at pomerium's Service.
  - The same application deploys its Service resource with annotations for "service class" (b) and pomerium-operator can pick up the configuration.
  - OR it can deploy a second Ingress resource for class (b), and pomerium-operator can pick up the resource and annotations.
  - A mutating webhook could potentially fix up Ingress resources but may play hell with helm 3.

- Inverted Double Ingress ([internet]->[pomerium]->[nginx])
  - pomerium-operator and the third party ingress are both deployed, but watch the same Ingress class.
  - pomerium-operator is configured to target all backend traffic to the other ingress controller's service internally.
  - An application need only deploy a single Ingress with Pomerium annotations in addition to anything specific to the third party ingress controller.
  - Third party ingress controller is configured to report the status of the pomerium-operator proxy so that external-dns functions correctly.
  - SSL limitations as noted above.

There are probably other combinations, but those are the ones that I found to be at least somewhat workable and retain general Ingress ecosystem semantics.

## Organization

I favor the nginx controller model over the traefik model - one application managing the deployment of another application - over the traefik model of baking all the Kubernetes logic into the proxy itself.  So, the plan was a second repo and command/container/etc which could leverage some of the guts of Pomerium (https://github.com/pomerium/pomerium/pull/380 and some follow-ups set us up for that).  

So far, it isn't designed as a side car or launcher.  Instead, it updates the Pomerium ConfigMap in the API server.  When we start managing SSL certificates, this model has problems.  We may need a small side car to at least inject SSL certificates to the filesystem where Pomerium can read them.  As mentioned before, I think the operator can grow to more than just ConfigMap management so I don't want to assume it will live inside the deployment.  This will need to be reconciled but I haven't spent too much time on it yet.

Eventually I would like to see the operator be the core of the helm chart.

## Roadmap

This is tentative but I'm mostly done with milestone 1.

1. Basic CM update functionality.  Provide enough functionality to implement the Forward Auth deployment model.  Basically this is just policy updates being automated and compatible with the current helm chart.  

2. Introduce a mutating webhook that speaks the 3 forward auth dialects and annotates your Ingress for you.  Maybe introduce this configuration via CRD.

3. Get "table stakes" Ingress features into pomerium.  Target model is Inverted Double Ingress or Simple Ingress.  We need cert handling up to snuff, but load balancing and path based routing can be offloaded to a next-hop ingress controller or kube-proxy via Service.  CRD maps which "next-hop" service to use for the IDI model from the ingress class.

4.  Introduce backend load balancing via Endpoint discovery to allow for skipping a second ingress for most configurations.

5.  Allow non-Ingress/Service based policy via CRD.  Helm chart does conversion on the backend.

6.  Pomerium deployment itself is managed by CRD.  The helm chart becomes a wrapper to this CRD.  Move the templating and resource generation logic into pomerium-operator.

There's been discussion of adding more sophisticated policy logic to pomerium, which could make the simplistic annotations currently in milestone (1) hard to use.  This might turn into a way to link Ingress/Service resources to CRDs via annotation to specify more complex policy blocks while retaining ties to the core resource types.  

</Wall of Text>

## Spec

For milestone 1, here's the annotation spec:

| Key      | Description |
| ----------- | ----------- |
|`kubernetes.io/ingress.class`| standard kubernetes ingress class |
|`kubernetes.io/service.class`| class for service control.  effectively signals pomerium-operator to watch/configure this resource |
|`pomerium.ingress.kubernetes.io/backend-protocol`| set backend protocol to http or https.  similar to nginx|
|`ingress.pomerium.io/[policy_config_key]`| `policy_config_key` is mapped to a policy configuration of the same name in yaml form.  eg, `ingress.pomerium.io/allowed_groups` is mapped to `allowed_groups` in the policy block for all service targets in this Ingress.  This value should be JSON format.|

Current implementation supports fanout of policy generation from an Ingress.  If you have 8 Host<->Backend mappings, it will generate 8 policy entries.

I'm going to work with @desimone on moving the work into a Pomerium Org hosted repo this week.

**Comment by travisgroth** [comment]
Here we go https://github.com/pomerium/pomerium-operator.

**Comment by travisgroth** [comment]
@commixon the first RC of the pomerium operator has been integrated into our helm chart at https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/README.md#pomerium-operator-experimental

https://github.com/pomerium/pomerium-operator#using
https://github.com/pomerium/pomerium-operator/releases

Not a full ingress controller at this time, as it leverages forward auth.  The plan is to move towards a full ingress controller, but that depends on a few factors.  Please report any issues or suggestions!  

If you don't mind, we'll close this out and can shift further feature/improvement discussions into the operator repo.
