### ISSUE TITLE
Diplay group `DisplayName` in the UI

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#578]
**Is your feature request related to a problem? Please describe.**

It would be nice if the the `/.pomerium` endpoint could **also** show the display name of the user's groups.

I don't know how it is for others but with Azure AD the groups are UUID so not really easy to work with.

<img width="700" alt="Pomerium" src="https://user-images.githubusercontent.com/153052/78123015-d549c580-740d-11ea-9a54-863860a64925.png">

Regards.

**Comment by desimone** [comment]
Related #573

**Comment by desimone** [comment]
@sylr This should be fixed in master, though I can't recall the exact issue it was fixed in.

By default, the group name will be shown in the UI, but if you hover over the elemnt it will show the guid.

<img width="1215" alt="Screen Shot 2020-09-06 at 4 53 47 PM" src="https://user-images.githubusercontent.com/1544881/92337958-d4265f80-f061-11ea-8226-b70447adfb00.png">
