### ISSUE TITLE
proxy : authorize_internal_url is extraneous 

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#66]
Hi,

If I set on the proxy the two `AUTHORIZE_INTERNAL_URL` and `AUTHENTICATE_INTERNAL_URL`, then pomerium complains that `AUTHORIZE_SERVICE_URL` and `AUTHENTICATE_SERVICE_URL` are not set.

I would expect that if the proxy is using the internal urls, it does not need to know about the external urls, does it?

**Comment by victornoel** [comment]
Actually, what I said is incorrect because `AUTHENTICATE_SERVICE_URL` is also used during sign in (`AUTHENTICATE_SERVICE_URL/sign_in`).

**Comment by desimone** [comment]
Meant to respond to this earlier but we had some back and forth in the helm issue referenced above. @victornoel is correct. Though we need both AUTHENTICATE_* config settings (one for the http handler which is externally routed and one for the potentially internally routed gRPC service) authorize only has a gRPC service we we don't need an override. 

I've held off on changing this setting because it's a little confusing to explain but I think we should remove the duplicate setting. This is a bug.
