### ISSUE TITLE
Method to run as non-root user

### ISSUE THREAD

**Issue by ross-w** [pomerium/pomerium#835]
I have noticed that Pomerium and Envoy run as root (at least when using the all in one container.) While it might be necessary to run as root initially to bind ports and the like, it would be great if they could drop privileges as soon as practical.

It may also be impossible, when running in a more restrictive Kubernetes environment, to have pods running as root in the first place. This may necessitate using capabilities instead, rather than the root user.

Implementation wise this could be done either automatically, or, alternately, by taking in a configurable UID/GID in the configuration environment/file.

**Comment by travisgroth** [comment]
I'm not seeing a way to have Envoy drop privileges at this time, which makes this hard to implement in a generalized way.  If I'm mistaken, we'd be happy to look at any docs.  

We should be able to run as any user, but privileged ports will need root without special configuration.  For kubernetes specifically, there's been discussion in the helm chart repo on moving to user mapping to work around this but hasn't been fully investigated yet.  

All that said, the most portable way to accomplish this is probably to just not default to privileged ports and let load balancers or container mappings take care of abstracting it.  I could see this as part of the next release.  This change would require updates to a bunch of docs and the helm chart.  It would also be breaking behavior.  However, it would follow better privilege practices and would be worth pursuing further.

**Comment by ThorbenJ** [comment]
I run pomerium as it own user. You can give it low port bind permissions via capabilities (e.g. in its systemd service file) or use authbind --deep to start it.

**Comment by mihaitodor** [comment]
Not sure if this helps, but the startup script that the Envoy containers [use as entrypoint](https://github.com/envoyproxy/envoy/blob/f4a800fc8f657116243ded38bb9337e1d8112117/ci/Dockerfile-envoy-alpine#L14) is designed to allow running the envoy process as non-root: https://github.com/envoyproxy/envoy/blob/f4a800fc8f657116243ded38bb9337e1d8112117/ci/docker-entrypoint.sh#L25

**Comment by calebdoxsey** [comment]
It is already possible today to run the app as non-root if you don't bind 443 or use setcap to give it access. This is how I regularly test the app. What do we want to change?

**Comment by travisgroth** [comment]
As @calebdoxsey points out, our standard OS install can run without root as long as you don't bind to privileged ports.  The out of box os package uses 8443.

As far as container images go, because we use distroless for releases, this is harder than it sounds on paper without breaking a lot of deployments and documentation.

1) We need to fetch/build/include a binary like su-exec or gosu.  There's no fetching from apk.  I have a partial solution for that, though it's pretty gross.  Using `gosu` since they at least have builds published:

```Dockerfile
# download gosu for the current architecture
# ref: https://github.com/tianon/gosu/blob/master/INSTALL.md
FROM alpine as gosu
RUN apk add \
    curl \
    dpkg \
    gpg \
    dirmngr \
    gpg-agent

RUN GOSU_VERSION=1.14 \
    && ARCH="$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
    && curl -Lo /tmp/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-${ARCH}.asc" \
    && curl -Lo /tmp/gosu https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${ARCH} \
    && gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /tmp/gosu.asc /tmp/gosu \
    && chmod 755 /tmp/gosu

[...snip...]

COPY --from=gosu /tmp/gosu /bin
```

2) There's no shell for an entrypoint script to run in.  Solutions here:
  a) use alpine instead (trading off root for a less restrictive container environment)
  b) publish different images for rootless so the choice is explicit by the operator
  c) build an entrypoint in a compiled language (basically collapse gosu and the concept of an entrypoint script) or execute envoy as non-root given certain flags
  d) other ideas?


Another possible approach that addresses both (1) and (2) would be to include a newer [`setpriv`](https://man7.org/linux/man-pages/man1/setpriv.1.html) into the distroless image to support changing uid and capabilities but it seems to require other libraries that aren't included.  The version of `setpriv` that is included with distroless images doesn't support setting capabilities so we still need to perform some logic to determine if we should change users.

The nuclear option is, of course, to change the default port entirely and assume non-root.  This would break some documentation and all container deployments as well as our default ports.

I'm not sure there's a great answer here though the most cut and dry is independent images with the tag `nonroot`.  It complicates the release process a bit, but allows for very explicit opt-in built on the distroless `nonroot` upstream image.  Would be interested in any thoughts from the community.

**Comment by travisgroth** [comment]
Some additional news...it looks like docker now sets the unprivileged port range to start at 0 on containers by default.  https://github.com/moby/moby/pull/41030.  This isn't universal and will vary by container runtime, so a separate image is probably a good starting point but we might be able to safely default to non-root in the near future.
