### ISSUE TITLE
handleForwardAuth in grpc should handle implicit url (x-forwarded headers)

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#860]
## What happened?

I'm going to preface with this is my first time writing in Go, so I didn't want to submit pull requests that are probably not great.  You can take a look at my fork if you want to investigate how I've resolved this issue/feature.  My environment is Pomerium/Traefik (forward auth)/Keycloak.

Looking at the logic in the handleForwardAuth function, it's looking for the explicit "uri" redirect only.  The forward auth handler in the proxy also handles implicit verification through the x-forwarded headers that Traefik (and other reverse proxies) can provide.

## What did you expect to happen?

handleForwardAuth should probably (though perhaps I'm misreading the purpose) handle implicit redirects as well (like the proxy) to determine if in forward auth mode.

## What's your environment like?

- Pomerium 0.9.0
- Traefik 2.2.1
- Keycloak
## What's your config.yaml?

Not Applicable

## What did you see in the logs?

Not Applicable

**Comment by cuonglm** [comment]
@simbaja I believe this problem happens due to deduplicate handling logic in proxy and authorize. This should not the case anymore after #1030 . Now, the proxy will forward the forward auth request as-is to the authorize, and when composing check request in authorize, it does honor `X-Forwarded-Uri` header.

Closing it for now, feel free to re-open if you think it's still a problem.
