### ISSUE TITLE
Proxy: Allow mapping apex external host url to backend path

### ISSUE THREAD

**Issue by cjwalton** [pomerium/pomerium#880]
Some backend applications may require a non-apex path. I'd like to be able to craft a policy statement to map to a path. This is more elegant than trying to fix this on the backend application.

Example:

  - from: https://myapp.external.domain
    to: https://myapp.internal.domain/app

Currently, it seems Pomerium only supports statements like this:

  - from: https://myapp.external.domain
    to: https://myapp.internal.domain

**Comment by Vad1mo** [comment]
This is what `pather` - `prefix` are for. did you take a look at https://www.pomerium.io/configuration/#path? https://www.pomerium.io/docs/upgrading.html#using-paths-in-from-urls

**Comment by calebdoxsey** [comment]
@Vad1mo I think @cjwalton wants to support stripping/adding prefixes. ie `https://myapp.external.domain/some/path` becomes `https://myapp.internal.domain/app/some/path`. That's not currently supported. 

We can support a basic string literal pretty easily, but some of the other options would be harder. (like a regular expression match) I'm also not sure what the configuration should look like. We explicitly disabled paths in the `from` parameter because it's ambiguous how they should be interpreted, but I guess a path in the `to` parameter wouldn't have that issue. But then we're only supporting adding the prefix, not stripping it, so maybe it should be an entirely different configuration option.

**Comment by cjwalton** [comment]
@calebdoxsey  is correct. Specifically I am looking for a path added to the "to" parameter. 
from: host.local
to: host.local/app
