### ISSUE TITLE
Auto port discovery on Docker containers

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#91]
This is a bit stretch because Pomerium may not be running on a server with Docker at all.

But for people who run Pomerium in Docker and want to proxy request to other containers, it would be super useful to only specify the hostname (the container name if they are connected to the same network) and let Pomerium to discover the exposed ports. If there are more than 1 exposed port, just randomly pick one and raise error if it's not an HTTP port.

E.g. if I have a container named `example` that have `exposes:8181`, I should be able to specify this in policy file and let Pomerium to do the port discovery:

```
- from: external.example.com
  to: http://example
  ...
```

Without this I would probably run https://github.com/jwilder/nginx-proxy or https://traefik.io/ as an additional layer of proxy.

**Comment by desimone** [comment]
I see what you are saying, but I'd prefer we didn't include this type of lookup code in pomerium's base just because I worry about the carry-forward implications of randomly picking a configuration value that may fail. 

Depending on your environment, I think putting nginx-proxy or the like makes a lot of sense and gives the benefits of a full fledge load balancer which also is helpful if you want to do any service scaling. 

The [nginx microservices example](https://www.pomerium.io/docs/examples.html#docker) maybe a good fit for those looking for this type of functionality.
